# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include base setup
  ansible.builtin.include_tasks: environment-setup.yml

- name: Mark existing APT repositories as x86/64
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^deb h'
    replace: 'deb [arch=amd64,i386] h'

- name: Enable ARM64 architecture
  ansible.builtin.command: dpkg --add-architecture arm64

- name: Add Ubuntu main repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }} main restricted universe multiverse
    state: present

- name: Add Ubuntu updates repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }}-updates main restricted universe multiverse
    state: present

- name: Add Ubuntu backports repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }}-backports main restricted universe multiverse
    state: present

- name: Install the additional Open Enclave prerequisites APT packages for ARM development
  ansible.builtin.apt:
    name: "{{ apt_arm_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no

- name: Install the additional distribution-specific Open Enclave prerequisites APT packages for ARM development
  ansible.builtin.apt:
    name: "{{ apt_arm_distribution_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no
  when:
    - apt_arm_distribution_packages is defined
    - apt_arm_distribution_packages | length > 0
