# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  setup:

- import_role:
    name: linux/common
    tasks_from: apt-repo-microsoft.yml

- import_role:
    name: linux/common
    tasks_from: apt-repo-llvm.yml

- name: Include vars
  include_vars:
    file: "{{ ansible_distribution_release | lower }}.yml"

- name: Install all the Open Enclave prerequisites APT packages for development
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes
    install_recommends: no

- import_role:
    name: linux/openenclave
    tasks_from: opam-setup.yml

- name: Install CMake 3.13.1
  unarchive:
    src: https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Create CMake symbolic links
  file:
    src: "/usr/local/cmake-3.13.1-Linux-x86_64/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    force: yes
    state: link
  with_items:
    - ccmake
    - cmake
    - cpack
    - ctest
