# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
cmake_target_version: "3.13.1"
clang_target_version: "11.1.0"
shellcheck_target_version: "0.4.6"
cmake_prefix: "/usr/local"

clang_binary_name: "clang-11"

apt_packages:
  - "curl"
  - "make"
  - "ninja-build"
  - "shellcheck"
  - "gcc"
  - "g++"
  - "gdb"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
  - "libcurl4-openssl-dev"
  - "libx11-dev"
  - "libncurses5-dev"
  - "unzip"
  - "python"
  - "clang-11"
  - "clang-format-11"
  - "llvm-11"
  - "lldb-11"
  - "python3-lldb-11"
  - "clang-10"
  - "clang-format-10"
  - "lldb-10"

apt_arm_packages:
  - "gcc-arm-linux-gnueabi"
  - "gcc-arm-linux-gnueabihf"
  - "gcc-aarch64-linux-gnu"
  - "g++-aarch64-linux-gnu"
  - "python-crypto"
  - "libc6-dev:arm64"
  - "libssl-dev:arm64"
  - "libfdt1"
  - "openssh-client"
  - "sshpass"

validation_distribution_binaries:
  - "/usr/bin/shellcheck"
  - "/usr/bin/clang-11"
  - "/usr/bin/clang-10"

validation_distribution_files:
  - "/usr/lib/x86_64-linux-gnu/libssl.so"
