# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key"
    apt_repository: "deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu {{ ansible_distribution_release }} main"

- name: Install the Intel libsgx package dependencies
  apt:
    name: "{{ intel_sgx_package_dependencies }}"
    state: latest
    update_cache: yes
    install_recommends: no

- name: Install the Intel libsgx packages
  apt:
    name: "{{ intel_sgx_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no

- name: Install the Intel DCAP packages
  apt:
    name: "{{ intel_dcap_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no
  when: flc_enabled|bool

- name: Install the Intel enclave launch package
  apt:
    name: "{{ intel_sgx_launch_package }}"
    state: latest
    update_cache: yes
    install_recommends: no
  when: not flc_enabled|bool
