# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2
jobs:
  # check-precommit-reqs test - check license and formatting info
  check-precommit-reqs-test:
    docker:
      - image: oeciteam/oetools:1.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Merge master to your branch; check if not master
      - run: 
          name: Check-Precommit-Reqs Test
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               #git config --global user.email "oeciteam@microsoft.com"
               #git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/check-precommit-reqs 

  #========Build-Test==========# 

  # SGX1 | Debug 
  ci-sgx1-debug:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-Debug
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config 

  # SGX1 | RelWithDebInfo
  ci-sgx1-relwithdebinfo:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-RelWithDebInfo
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config -p SGX1 -b RelWithDebInfo
  
  # SGX1 | Release
  ci-sgx1-release:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-Release
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config -p SGX1 -b Release
             
  # SGX1-FLC | Debug 
  ci-sgx1-flc-debug:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config -p SGX1FLC -b Debug 
            
  # SGX1-FLC | RelWithDebInfo
  ci-sgx1-flc-relwithdebinfo:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-RelWithDebInfo
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config -p SGX1FLC -b RelWithDebInfo 

  # SGX1-FLC | Release 
  ci-sgx1-flc-release:
    docker:
      - image: oeciteam/oetools:1.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Release
          command: | 
            if [ ${CIRCLE_BRANCH} != "master" ]; then
               echo "Merging master to your branch ${CIRCLE_BRANCH}"
               git config --global user.email "oeciteam@microsoft.com"
               git config --global user.name "OE CI Team"
               git pull origin master --no-edit
            fi
            ./scripts/test-build-config -p SGX1FLC -b Release
             
workflows:
  version: 2
  ci-test:
    jobs:
      # 1. Check-Precommit-Reqs test
      - check-precommit-reqs-test
      
      # 2. sgx1-debug(ci-test)
      - ci-sgx1-debug:
          requires:
            - check-precommit-reqs-test
            
      # 3. sgx1-relwithdebinfo(ci-test)     
      - ci-sgx1-relwithdebinfo:
          requires:
            - check-precommit-reqs-test
            
      # 4.  sgx1-release(ci-test)    
      - ci-sgx1-release:
          requires:
             - check-precommit-reqs-test
            
      # 5.  sgx1-flc-debug(ci-test)
      - ci-sgx1-flc-debug:
          requires:
            - check-precommit-reqs-test
            
      # 6.  sgx1-flc-relwithdebinfo(ci-test)  
      - ci-sgx1-flc-relwithdebinfo:
          requires:
            - check-precommit-reqs-test
            
      # 7.  sgx1-flc-release(ci-test)    
      - ci-sgx1-flc-release:
         requires:
            - check-precommit-reqs-test

