# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
intel_sgx_packages:
  - "libsgx-enclave-common"
  - "libsgx-ae-qve"
  - "libsgx-ae-pce"
  - "libsgx-ae-qe3"
  - "libsgx-qe3-logic"
  - "libsgx-pce-logic"

intel_dcap_packages:
  - "libsgx-dcap-ql"
  - "libsgx-dcap-ql-dev"
  - "libsgx-urts"
  - "libsgx-quote-ex"
  - "sgx-aesm-service"
  - "libsgx-aesm-ecdsa-plugin"
  - "libsgx-aesm-pce-plugin"
  - "libsgx-aesm-quote-ex-plugin"

packages_validation_distribution_files:
  - "/usr/lib/x86_64-linux-gnu/libsgx_enclave_common.so.1"
  - "/usr/lib/x86_64-linux-gnu/libsgx_pce_logic.so"
  - "/usr/lib/x86_64-linux-gnu/libsgx_qe3_logic.so"
  - "/usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so"
