# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Jenkins | Set default host variables (if not already set by the user)
  block:
    - set_fact:
        jenkins_agent_name: "{{ ansible_hostname }}"
      when: jenkins_agent_name is not defined

    - set_fact:
        jenkins_agent_executors_count: 1
      when: jenkins_agent_executors_count is not defined

    - set_fact:
        jenkins_agent_label: ""
      when: jenkins_agent_label is not defined

    - set_fact:
        jenkins_agent_root_dir: "/home/jenkins"
      when: jenkins_agent_root_dir is not defined

- name: Jenkins | Check if the node already exists
  jenkins_script:
    script: jenkins.model.Jenkins.getInstance().getComputer("{{ jenkins_agent_name }}")
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_name }}"
    password: "{{ jenkins_admin_password }}"
  register: script_output

- name: Jenkins | Create the node if it doesn't exist already
  jenkins_script:
    script: |
      import jenkins.model.*
      import hudson.model.*
      import hudson.slaves.*

      Slave agent = new DumbSlave(
          "{{ jenkins_agent_name }}",
          "{{ jenkins_agent_root_dir }}",
          new JNLPLauncher()
      )
      agent.setNumExecutors({{ jenkins_agent_executors_count }})
      agent.setLabelString("{{ jenkins_agent_label }}")
      agent.setMode(Node.Mode.NORMAL)
      agent.setRetentionStrategy(new RetentionStrategy.Always())

      Jenkins.instance.addNode(agent)

    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_name }}"
    password: "{{ jenkins_admin_password }}"
  when: (script_output.output.lstrip('Result:') | trim) == ""

- name: Jenkins | Extract the Jenkins agent secret
  jenkins_script:
    script: jenkins.model.Jenkins.getInstance().getComputer("{{ jenkins_agent_name }}").getJnlpMac()
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_name }}"
    password: "{{ jenkins_admin_password }}"
  register: script_output

- set_fact: 
    node_secret="{{script_output.output.lstrip('Result:') | trim}}"
