# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Check for existing required folders and files
  ansible.windows.win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_directories }}"
  register: directory
  failed_when: not directory.stat.isdir

- name: Check for existing required executables and files
  ansible.windows.win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries + validation_files }}"
  register: file
  failed_when: not file.stat.isreg

- name: CMake version check
  ansible.windows.win_command: vcvars64.bat x64 && cmake --version
  register: cmake_check_version
  failed_when: cmake_check_version.stdout.find(cmake_target_version) == -1

- name: Ninja version check
  ansible.windows.win_command: vcvars64.bat x64 && ninja --version
  register: ninja_check_version
  failed_when: ninja_check_version.stdout.find(ninja_target_version) == -1

- name: Clang version check
  ansible.builtin.raw: "& 'C:\\Program Files\\LLVM\\bin\\clang.exe' --version"
  register: clang_check_version
  failed_when: clang_check_version.stdout.find(clang_target_version) == -1
  args:
    executable: ansible.windows.win_shell

- name: Previous Clang version check
  ansible.builtin.raw: "& 'C:\\Program Files\\LLVM-previous\\bin\\clang.exe' --version"
  register: previous_clang_check_version
  failed_when: previous_clang_check_version.stdout.find(previous_clang_version) == -1
  args:
    executable: ansible.windows.win_shell
