# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Add Microsoft repository
  ansible.builtin.include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    apt_repository: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"

- name: Add llvm repository
  ansible.builtin.include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    apt_repository: "{{ llvm_apt_repository }}"
  when: 
    - llvm_apt_repository is defined
    - ansible_distribution_release != 'jammy' # LLVM repo does not have 11 for Jammy but is available via standard Ubuntu repo

- name: Install all the Open Enclave prerequisites APT packages for development
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no
  retries: 100
  register: install
  until: install is success
