# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
intel_sgx_packages:
  - "libsgx-enclave-common"
  - "libsgx-enclave-common-dev"
  - "libsgx-urts"
  - "libsgx-ae-qve"
  - "libsgx-ae-pce"
  - "libsgx-ae-qe3"

intel_dcap_packages:
  - "libsgx-dcap-ql"
  - "libsgx-dcap-ql-dev"

driver_validation_directories:
  - "/opt/intel/sgxdriver"

packages_validation_files:
  - "/usr/lib/x86_64-linux-gnu/libsgx_enclave_common.so"
  - "/usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so"
  - "/usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so"
