# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  setup:

- name: Include distribution release specific vars
  include_vars:
    file: "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"

- name: Install Docker prerequisite packages
  apt:
    name: "{{ ci_apt_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no

# Workaround for Ubuntu 18.04 Docker container tests
# https://github.com/intel/linux-sgx/blob/a85fbe9a55767681b0f799a66555b123312fb72c/linux/installer/common/psw/install.sh#L66-L99
- name: Create /etc/init directory
  file:
    path: /etc/init
    state: directory

- import_role:
    name: linux/openenclave
    tasks_from: environment-setup.yml

- import_role:
    name: linux/openenclave
    tasks_from: environment-setup-cross-arm.yml

- import_role:
    name: linux/intel
    tasks_from: sgx-packages.yml

- import_role:
    name: linux/az-dcap-client
    tasks_from: stable-install.yml
