# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- name: Add LLVM and Microsoft APT repo keys
  apt_key: url={{item}} state=present
  with_items:
    - https://apt.llvm.org/llvm-snapshot.gpg.key
    - https://packages.microsoft.com/keys/microsoft.asc

- name: Add LLVM and Microsoft APT repositories
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main
    - deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main

- name: Add LLVM and Microsoft APT repositories
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main
    - deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main

- name: Install  prerequisites and Intel and Open Enclave packages
  apt:
    name: [
      clang-7,
      libssl-dev,
      make,
      gcc,
      gdb,
      g++,
      pkg-config,
      az-dcap-client
    ]
    state: present
    update_cache: yes
