# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- name: Add LLVM repo keys
  apt_key: url="https://apt.llvm.org/llvm-snapshot.gpg.key" state=present

- name: Add LLVM repo for CLang 7 with Spectre mitigation
  apt_repository: repo="deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" state=present update_cache=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Add LLVM repo for CLan7 with Spectre mitigation
  apt_repository: repo="deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" state=present update_cache=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'

- name: Install Clang 7 to build with Spectre mitigation
  apt:
    name: clang-7
    state: present
    install_recommends: no

- name: Install  prerequisite packages
  apt:
    name: [
       apt-transport-https,
       autoconf,
       clang-format-7,
       doxygen,
       gdb,
       graphviz,
       libexpat1-dev,
       libssl-dev,
       libtool,
       make,
       ocaml-native-compilers,
       openssl,
       pkg-config,
       shellcheck,
       subversion
    ]
    state: present
    update_cache: yes

# This will unpack the archive in / then rename the /cmake-3.13.1-Linux-x86_64 folder into /cmake
- name: Install CMake 3.13.1
  unarchive:
    src: https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Create CMake symbolic links
  file:
    src: "/usr/local/cmake-3.13.1-Linux-x86_64/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
  - ccmake
  - cmake
  - cpack
  - ctest
