# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- name: Download Intel SGX DCAP Driver
  get_url:
    url: https://download.01.org/intel-sgx/dcap-1.0/sgx_linux_x64_driver_dcap_36594a7.bin
    dest: /tmp/sgx_linux_x64_driver_dcap_36594a7.bin
    mode: 0755

- name: Install the Intel SGX DCAP Driver
  command: /tmp/sgx_linux_x64_driver_dcap_36594a7.bin

- name: Remove the Intel SGX DCAP Driver installer
  file: path=/tmp/sgx_linux_x64_driver_dcap_36594a7.bin state=absent
