# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
apt_packages:
  - "clang-7=1:7.0.1~svn348686-1~exp1~20181221231927.53"
  - "clang-format-7=1:7.0.1~svn348686-1~exp1~20181221231927.53"
  - "make=4.1-6"
  - "ocaml-native-compilers=4.02.3-5ubuntu2"
  - "ninja-build=1.5.1-0.1ubuntu1"
  - "shellcheck=0.3.7-5"
  - "gcc=4:5.3.1-1ubuntu1"
  - "g++=4:5.3.1-1ubuntu1"
  - "gdb=7.11.1-0ubuntu1~16.5"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
