# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
- hosts: "{{ target }}"
  any_errors_fatal: true
  become: yes
  tasks:
  - include_tasks: tasks/ansible-install-docker-packages.yml
  - include_tasks: tasks/ansible-install-prereqs.yml
  - include_tasks: tasks/ansible-install-openenclave-deps.yml
  - include_tasks: tasks/ansible-install-sgx-packages.yml
