# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

- hosts: linux-slaves
  any_errors_fatal: true
  become: yes
  vars_files:
     - vars/variables.var
  tasks:
     - include_tasks: tasks/ansible-install-prereqs.yml
     - include_tasks: tasks/ansible-install-openenclave-deps.yml
     - include_tasks: tasks/ansible-install-sgx-driver.yml
     - include_tasks: tasks/ansible-install-sgx-packages.yml
     - include_tasks: tasks/ansible-install-az-dcap-client.yml

     - name: Provision new linux slave node
       jenkins_script:
         script: "{{ lookup('template', '../templates/linux_slave.groovy.j2') }}"
         user: "{{ jenkins_master_user }}"
         password: "{{ jenkins_master_password }}"
         url: "{{ jenkins_master }}"

     - name: Extract slave secret
       jenkins_script:
         script: jenkins.model.Jenkins.getInstance().getComputer("{{ jenkins_slave_name }}").getJnlpMac()
         user: "{{ jenkins_master_user }}"
         password: "{{ jenkins_master_password }}"
         url: "{{ jenkins_master }}"
       register: script_output

     - set_fact: node_secret="{{script_output.output.lstrip('Result:') | trim}}"

     - name: Install jre needed by Jenkins
       apt: name{{item}} state=present update_cache=yes
       with_items:
               - openjdk-8-jre
     - name: Create the jenkins group
       group:
               name: jenkins
               state: present
     - name: Add the Jenkins user
       user:
            name: jenkins
            group: jenkins
     - name: Add repositories for docker
       apt_repository: repo={{item}} state=present update_cache=yes
       with_items:
               - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
     - name: Add docker repository key
       apt_key: url={{item}} state=present
       with_items:
       - https://download.docker.com/linux/ubuntu/gpg
     - name: Install prerequisite packages
       apt: name{{item}} state=present update_cache=yes
       with_items:
               - docker-ce
     - name: Add jenkins to the docker group
       user:
         name: jenkins
         groups: docker
     - name: Setup JNLP Slave
       import_role:
         name: kobanyan.jenkins-jnlp-slave
       vars:
         jenkins_slave_secret: "{{ node_secret }}"
