# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

- hosts: localhost
  any_errors_fatal: true
  tasks:
     - include_tasks: tasks/ansible-install-prereqs.yml
     - include_tasks: tasks/ansible-install-openenclave-deps.yml
     - include_tasks: tasks/ansible-install-sgx-driver.yml
     - include_tasks: tasks/ansible-install-sgx-packages.yml
     - include_tasks: tasks/ansible-install-openenclave.yml
     - include_tasks: tasks/ansible-install-az-dcap-client.yml
