# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - name: OE setup | Set installer URLs from the OE storage account
      set_fact:
        intel_psw_2_2_url:   "https://oejenkins.blob.core.windows.net/oejenkins/intel_sgx_win_2.2.100.47975_PV.zip"
        intel_psw_2_2_hash:  "EB479D1E029D51E48E534C284FCF5CCA3A937DA43052DCB2F4C71E5F354CA623"
        intel_psw_2_4_url:   "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20PSW%20for%20Windows%20v2.4.100.51291.exe"
        intel_psw_2_4_hash:  "79AE32E984B5511CE4BF7568403333F837FBCE7E8D5730271C5D68F55BBF251D"
        intel_dcap_url:      "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20DCAP%20for%20Windows%20v1.2.100.49925.exe"
        intel_dcap_hash:     "F31E4451CA32E19CA3DCB0AFC49AFE9F4963C47BF62AAF24A8AE436BDA14FD8B"
        git_url:             "https://oejenkins.blob.core.windows.net/oejenkins/Git-2.19.1-64-bit.exe"
        git_hash:            "5E11205840937DD4DFA4A2A7943D08DA7443FAA41D92CCC5DAFBB4F82E724793"
        seven_zip_url:       "https://oejenkins.blob.core.windows.net/oejenkins/7z1806-x64.msi"
        seven_zip_hash:      "F00E1588ED54DDF633D8652EB89D0A8F95BD80CCCFC3EED362D81927BEC05AA5"
        vs_buildtools_2017:  "https://oejenkins.blob.core.windows.net/oejenkins/vs_buildtools_2017.exe"
        vs_buildtools_hash:  "6F49872B04A0EAEDF5ED96AB25F7697062D81A419D45D9970E41784F31165BF2"
        ocaml_url:           "https://oejenkins.blob.core.windows.net/oejenkins/ocpwin64-20160113-4.02.1+ocp1-mingw64.zip"
        ocaml_hash:          "369F900F7CDA543ABF674520ED6004CC75008E10BEED0D34845E8A42866D0F3A"
        clang7_url:          "https://oejenkins.blob.core.windows.net/oejenkins/LLVM-7.0.1-win64.exe"
        clang7_hash:         "672E4C420D6543A8A9F8EC5F1E5F283D88AC2155EF4C57232A399160A02BFF57"
        shellcheck_url:      "https://oejenkins.blob.core.windows.net/oejenkins/shellcheck-stable.exe"
        shellcheck_hash:     "3026F9598C8C62E5F7EE3DBADFA9254AD4DAC925B2AE1B1A15D8052D858C465A"
        nuget_url:           "https://oejenkins.blob.core.windows.net/oejenkins/nuget.exe"
        nuget_hash:          "3E41E6E736441198C3E7FFCED751D1F0E9755BEDCAABF07BAED413F08F635B9B"
        devcon_package_url:  "https://oejenkins.blob.core.windows.net/oejenkins/devcon_package.cab"
        devcon_package_hash: "A38E409617FC89D0BA1224C31E42AF4344013FEA046D2248E4B9E03F67D5908A"
        az_dcap_client_url:  "https://oejenkins.blob.core.windows.net/oejenkins/Microsoft.Azure.DCAP.Client.1.0.0.nupkg"
        az_dcap_client_hash: "152ACE956348E80E533E63E6CB1D3CA20E4CA7DC775FC0B9413F552368F971D6"

    - name: OE setup | Run the install-windows-prereqs.ps1 script (this may take a while)
      script: ../install-windows-prereqs.ps1
        -InstallPath        "C:\openenclave"
        -IntelPSWURL        "{{ intel_psw_2_4_url if dcap_testing_node is defined and dcap_testing_node == true else intel_psw_2_2_url }}"
        -IntelPSWHash       "{{ intel_psw_2_4_hash if dcap_testing_node is defined and dcap_testing_node == true else intel_psw_2_2_hash }}"
        -IntelDCAPURL       "{{ intel_dcap_url }}"
        -IntelDCAPHash      "{{ intel_dcap_hash }}"
        -GitURL             "{{ git_url }}"
        -GitHash            "{{ git_hash }}"
        -SevenZipURL        "{{ seven_zip_url }}"
        -SevenZipHash       "{{ seven_zip_hash }}"
        -VSBuildToolsURL    "{{ vs_buildtools_2017 }}"
        -VSBuildToolsHash   "{{ vs_buildtools_2017_hash }}"
        -OCamlURL           "{{ ocaml_url }}"
        -OCamlHash          "{{ ocaml_hash }}"
        -Clang7URL          "{{ clang7_url }}"
        -Clang7Hash         "{{ clang7_hash }}"
        -ShellCheckURL      "{{ shellcheck_url }}"
        -ShellCheckHash     "{{ shellcheck_hash }}"
        -NugetURL           "{{ nuget_url }}"
        -NugetHash          "{{ nuget_hash }}"
        -DevconURL          "{{ devcon_package_url }}"
        -DevconHash         "{{ devcon_package_hash }}"
        -AzureDCAPNupkgURL  "{{ az_dcap_client_url }}"
        -AzureDCAPNupkgHash "{{ az_dcap_client_hash }}"

    - name: OE setup | Reboot the node
      win_reboot:

    - import_role:
        name: windows/openenclave
        tasks_from: validation.yml

    - import_role:
        name: windows/az-dcap-client
        tasks_from: validation.yml
