# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - name: OE setup | Set installer URLs from the OE storage account
      set_fact:
        intel_psw_url:       "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20PSW%20for%20Windows%20v2.7.101.2.exe"
        intel_psw_hash:      "AF669A4593411E9AABCE18838C91003866DDDEDAC5BEEC61DE160025008B0A19"
        intel_dcap_url:      "https://oejenkins.blob.core.windows.net/oejenkins/Intel%20SGX%20DCAP%20for%20Windows%20v1.6.100.2.exe"
        intel_dcap_hash:     "39DB3E183E79400A4A1C635E67A927C8E5C75A19E5A2A7FC537E1B24D8FDF42E"
        git_url:             "https://oejenkins.blob.core.windows.net/oejenkins/Git-2.19.1-64-bit.exe"
        git_hash:            "5E11205840937DD4DFA4A2A7943D08DA7443FAA41D92CCC5DAFBB4F82E724793"
        seven_zip_url:       "https://oejenkins.blob.core.windows.net/oejenkins/7z1806-x64.msi"
        seven_zip_hash:      "F00E1588ED54DDF633D8652EB89D0A8F95BD80CCCFC3EED362D81927BEC05AA5"
        vs_buildtools:       "https://oejenkins.blob.core.windows.net/oejenkins/vs_buildtools_2017.exe"
        vs_buildtools_hash:  "6F49872B04A0EAEDF5ED96AB25F7697062D81A419D45D9970E41784F31165BF2"
        node_url:            "https://oejenkins.blob.core.windows.net/oejenkins/node-v10.16.3-x64.msi"
        node_hash:           "f68b75eea46232adb8fd38126c977dc244166d29e7c6cd2df930b460c38590a9"
        clang7_url:          "https://oejenkins.blob.core.windows.net/oejenkins/LLVM-7.0.1-win64.exe"
        clang7_hash:         "672E4C420D6543A8A9F8EC5F1E5F283D88AC2155EF4C57232A399160A02BFF57"
        shellcheck_url:      "https://oejenkins.blob.core.windows.net/oejenkins/shellcheck-v0.7.0.zip"
        shellcheck_hash:     "02CFA14220C8154BB7C97909E80E74D3A7FE2CBB7D80AC32ADCAC7988A95E387"
        nuget_url:           "https://oejenkins.blob.core.windows.net/oejenkins/nuget-3.4.3.nupkg"
        nuget_hash:          "2D4D38666E5C7D27EE487C60C9637BD9DD63795A117F0E0EDC68C55EE6DFB71F"
        devcon_package_url:  "https://oejenkins.blob.core.windows.net/oejenkins/devcon_package.cab"
        devcon_package_hash: "A38E409617FC89D0BA1224C31E42AF4344013FEA046D2248E4B9E03F67D5908A"
        az_dcap_client_url:  "https://oejenkins.blob.core.windows.net/oejenkins/microsoft.azure.dcap.1.4.2.nupkg"
        az_dcap_client_hash: "D1EB6842CE2F3E1243298A440743687BD16FE6B2AF9F1745837D4C445EA0A930"
        nsis_url:            "https://oejenkins.blob.core.windows.net/oejenkins/nsis-3.05-setup.exe"
        nsis_hash:           "1A3CC9401667547B9B9327A177B13485F7C59C2303D4B6183E7BC9E6C8D6BFDB"

    - name: OE setup | Run the install-windows-prereqs.ps1 script (this may take a while)
      script: ../install-windows-prereqs.ps1
        -InstallPath         "C:\oe_prereqs"
        -LaunchConfiguration "{{ launch_configuration }}"
        -DCAPClientType      "Azure"
        -IntelPSWURL         "{{ intel_psw_url }}"
        -IntelPSWHash        "{{ intel_psw_hash }}"
        -IntelDCAPURL        "{{ intel_dcap_url }}"
        -IntelDCAPHash       "{{ intel_dcap_hash }}"
        -GitURL              "{{ git_url }}"
        -GitHash             "{{ git_hash }}"
        -SevenZipURL         "{{ seven_zip_url }}"
        -SevenZipHash        "{{ seven_zip_hash }}"
        -VSBuildToolsURL     "{{ vs_buildtools }}"
        -VSBuildToolsHash    "{{ vs_buildtools_hash }}"
        -NodeURL             "{{ node_url }}"
        -NodeHash            "{{ node_hash }}"
        -Clang7URL           "{{ clang7_url }}"
        -Clang7Hash          "{{ clang7_hash }}"
        -ShellCheckURL       "{{ shellcheck_url }}"
        -ShellCheckHash      "{{ shellcheck_hash }}"
        -NugetURL            "{{ nuget_url }}"
        -NugetHash           "{{ nuget_hash }}"
        -DevconURL           "{{ devcon_package_url }}"
        -DevconHash          "{{ devcon_package_hash }}"
        -AzureDCAPNupkgURL   "{{ az_dcap_client_url }}"
        -AzureDCAPNupkgHash  "{{ az_dcap_client_hash }}"
        -NSISURL             "{{ nsis_url }}"
        -NSISHash            "{{ nsis_hash }}"

     # One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 3600

    - name: OE setup | Reboot the node
      win_reboot:

    - import_role:
        name: windows/openenclave
        tasks_from: validation.yml

    - import_role:
        name: windows/az-dcap-client
        tasks_from: validation.yml
